version: "3.8"

services:
  nvflare:
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-amd64} # The default is amd64
    image: nvflare-slim:latest
    ipc: host
    ports:
      - "18080-18085:18080-18085"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack: 67108864
    volumes:
      - ./my-workspace:/workspace/my-workspace
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]

